# Basic
title: Shuzhan Fan
author: Shuzhan Fan
description: Shuzhan Fan's personal website.

repository: shuzhanfan/shuzhanfan.github.io
baseurl: ""
url: https://shuzhanfan.github.io

permalink: /:year/:month/:title/

# Format
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "pages/:num/"

# Social
social:
    github: shuzhanfan
    mail: sfan2@lsu.edu

# Plugins
plugins:
    - jekyll-seo-tag

#Collections
collections:
    random-thoughts:
        output: true
        permalink: /:collection/:year/:month/:title/

# Staticman comments (full configuration in staticman.yml)
staticman:
    branch                 : "master"

# reCaptcha keys
reCaptcha:
    siteKey: "6Le4_T0UAAAAAJFB-3XtwuU86hxsw22z68niAPz3"
    secret: "6Le4_T0UAAAAAHv8J_MsFbGLRpwMBKFEtzv2SHv7"
