# Basic
title: Shuzhan Fan
author: Shuzhan Fan
description: Shuzhan Fan's personal website.

url: https://shuzhanfan.github.io

permalink: /:year/:month/:title/

# Format
markdown: kramdown
highlighter: rouge
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", tables]

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "pages/:num/"

# Social
social:
    github: shuzhanfan
    mail: sfan2@lsu.edu

# Plugins
plugins:
    - jekyll-seo-tag

#Collections
collections:
    random-thoughts:
        output: true
        permalink: /:collection/:year/:month/:title/
